sudo: false
language: node_js
node_js:
  - "8.3"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --frozen-lockfile
script:
  - npm install codecov -g
  - yarn test
after_success:
  - codecov
cache:
  yarn: true
env:
  - WEROBOT_BOT_CONFIG_PATH="./config.example.yml"