name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - name: Use Node.js to test and build
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: yarn build
    - uses: codecov/codecov-action@v1
      with:
        verbose: true
